FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache \
    chromium \
    nss \
    freetype \
    freetype-dev \
    harfbuzz \
    ca-certificates \
    ttf-freefont \
    python3 \
    make \
    g++

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 5173 3001

CMD ["npm", "run", "dev"]
